#!/bin/bash
# This script outputs the machine's uptime.

# Use the 'uptime' command to get information about the server's uptime
uptime_info=$(uptime)

# Use the 'hostname' command to get the machine's name
hostname_info=$(hostname)

# Extract the uptime part and remove the "load average" information
uptime=$(echo "$uptime_info" | awk -F, '{print $1}')

# Output the information about the machine's name and uptime
echo "Skriptimine at$uptime"
