#!/bin/bash
# See skript aitab bussiekskursioonide korraldajal arvutada, mitu bussitäit reisijaid on grupis ja mitu inimest on maha jäänud.

# Küsi kasutajalt reisijate arvu grupis
echo -n "Sisesta reisijate arv grupis: "
read reisijate_arv

# Küsi kasutajalt bussi kohtade arvu
echo -n "Sisesta bussi kohtade arv: "
read bussi_kohad

# Arvuta, mitu bussitäit reisijaid on grupis ja mitu inimest on maha jäänud
busside_arv=$((reisijate_arv / bussi_kohad))
mahajaanud=$((reisijate_arv % bussi_kohad))

# Väljasta tulemus
echo "Grupis on $busside_arv täis bussi ja $mahajaanud inimest on maha jäänud."

